### ISSUE TITLE
Failed to minify the code from this file:

### ISSUE THREAD

**Issue by GaneshBShinde** [adaltas/node-csv#233]
I have build react web app using 'react-script build' command.
I got the following error.

**Failed to minify the code from this file:

        ./node_modules/csv-generate/lib/index.js:69**

**Comment by wdavidw** [comment]
If this is related to including a code written in ES6, you could try to directly require 'csv-generate/lib/es5'.

**Comment by ats-developer** [comment]
Thank you @wdavidw , it's working. But i need to patch for every build.

**Comment by wdavidw** [comment]
Which patch do you need to apply?

**Comment by AdamBCo** [comment]
I'm running into the same issue.

What did you guys do to fix it? @ats-developer @wdavidw

**Comment by cheshire137** [comment]
Using create-react-app, `npm run build` fails with this error. I tried requiring the file mentioned above such that my imports look like this:

```javascript
import 'csv-generate/lib/es5'
import csv from 'csv'
```

But it still fails:

```
Failed to minify the code from this file:

        ./node_modules/csv-generate/lib/index.js:69

Read more here: http://bit.ly/2tRViJ9
```

Can the csv-generate package be published pre-compiled?

**Comment by wdavidw** [comment]
@cheshire137 
Why are you require `csv` if you required `csv-generate/lib/es5` just before?
Also, i'm not sure what you mean be pre-compiled.

**Comment by wdavidw** [comment]
Did you fix your issue ? Can we close it ?

**Comment by silawrenc** [comment]
Hi @wdavidw I was just about to open a related issue when I saw this. I think the problem here is the way that this package tries to support es5 compatibility. If you look at e.g. https://github.com/adaltas/node-csv/blob/master/lib/es5/index.js#L4 you can see that it's directly requiring the related package at index, and so getting the "es6" version, rather than requiring e.g. `csv-generate/lib/es5`. I can see that babel is used to generate this file, but babel generally won't transpile things it finds in `node_modules`, and so won't have any effect on the imported component packages.

Does that make sense? I'm happy to contribute a PR to fix this, although I can't think of a cleverer way of doing it that by effectively duplicating the existing file.

**Comment by silawrenc** [comment]
Awesome, thank you!

**Comment by wdavidw** [comment]
Latest version 5.0.1 should correct this issue.
