### ISSUE TITLE
Json Array to CSV file example

### ISSUE THREAD

**Issue by carson-nr** [adaltas/node-csv#254]
lack of clear examples that are along the lines of:

```
const data = [{key:"value1"},{key:"value2"}];

// probably is an async function
const csvString = csv.someUsefulFunction(data);

fs.writeFileSync("output.csv", csvString);
```

**Comment by Carson2006** [comment]
I can appreciate why this project was broken into multiple sub-projects, but it has forced me to take over work from less experienced developers because they are constantly lost in the documentation.

I admit that if I just want to make a csv file from some json data, I am tempted to use other libraries for their simplicity.

I would rather use this library due to the support for streams, as sometimes we work with very large data sets.

**Comment by wdavidw** [comment]
I am very open to suggestions to better and enrich de documentation. The website source code is entirely available on [GitHub](https://github.com/adaltas/node-csv) and I'll leave this issue open if you wish to discuss suggestions.

**Comment by Carson2006** [comment]
thank you for the response,

basically, I try to imagine that I know nothing about the library, but I want to sit down, and see an example of
1. turn a local CSV file into an array of JSON objects
2. turn an array of JSON objects into a CSV file 

I assumed we are to use csv-generate for this, but then csv generate only appears to be good for generating "random" data

I guess what I'm looking for is, what function turns an array of JSON data into a string that represents a csv file.

I'm sure I'm missing it, but I guess that's my point. :-)

**Comment by wdavidw** [comment]
Ok, it does make sense from a user perspective but technically, this library has nothing to do with reading or writing a file. This being said, while containing a lot of [examples on GitHub](https://github.com/adaltas/node-csv-parse/tree/master/samples), the examples section of each project should be split into multiple pages with an understable introduction presenting the code.

**Comment by carson-nr** [comment]
That sounds perfect! Thank you!
