### ISSUE TITLE
Github vulnerability warning in v1.2.0 - (csv > csv-parse)

### ISSUE THREAD

**Issue by VineetKumarKushwaha** [adaltas/node-csv#263]
We are using very old version v1.2.0 and getting below GitHub vulnerability warning related to csv-parse which is being used in your package.

```
  High            Regular Expression Denial of Service                          
                                                                                
  Package         csv-parse                                                     
                                                                                
  Dependency of   csv                                                           
                                                                                
  Path            csv > csv-parse                                               
                                                                                
  More info       https://npmjs.com/advisories/1171 
```

It would be very helpful if you can fix it and release one more version from v1. 
We will be migrating to the latest version but not in the 2020 scope so this change would help us.

**Comment by wdavidw** [comment]
You can send me a pull request with the suggested changes. I'll review it, merge it and publish a new 1.2.1 version. I honestly don't have the time to support old releases.

**Comment by ianmarcinkowski** [comment]
I am here reviewing `node-csv` as part of a security audit on one of my projects.  Our audit tools have identified this GH issue because it is open against `node-csv` and has the word "vulnerability" in the title and description.  This has come up in multiple of our private repo issues for review, so I thought I would dive a bit deeper!  I hope that's okay :)

After reviewing the purpose of this issue and taking a look at https://github.com/commercetools/sphere-stock-import/ it looks like the Original Poster's repository has updated to use `csv-parse` `^5.0.4` according to [their package-lock.json](https://github.com/commercetools/sphere-stock-import/blob/2b598189abeee7b182e534a029830e0f804fac7a/package-lock.json#L580-L590)

I believe this issue should be closed, as @VineetKumarKushwaha / `https://github.com/commercetools/sphere-stock-import` are no longer using v1.2.0 of csv-parse.

**Comment by wdavidw** [comment]
Sounds good to me.
