### ISSUE TITLE
File is always empty using createWriteStream trying to append

### ISSUE THREAD

**Issue by Zyles** [adaltas/node-csv#287]
**Describe the bug**

Been trying to get this working for a couple of hours now but I am unable to write object to csv file.

**To Reproduce**

```
const writeStream = fs.createWriteStream(`tmp/${filename}.${format}`, { encoding: 'utf8', flags : 'a' })
const data = [{
    name: '1',
  },
  {
    name: '2',
  },
]
stringify(data, {
  header: true,
}).write(writeStream)

const data 2= [{
    name: '3',
  },
  {
    name: '4',
  },
]
stringify(data2, {
  header: true,
}).write(writeStream)
```
File is created but file is empty.

Tried using `.pipe(writeStream)` instead but same issue.

How do you append to file?

Moving the createWriteStream into the pipe writes to the file, but not when creating it outside it. What is going on? Is it an async/await problem?
```
const data = [{
            name: '1',
          },
          {
            name: '2',
          },
        ]
        stringify(data, {
          header: true,
        }).pipe(fs.createWriteStream(`tmp/${filename}.${format}`, { encoding: 'utf8', flags : 'a' }))
```

**Comment by wdavidw** [comment]
I have no problem with pipe:

```js
const csv = require('csv')
const fs = require('fs')

const writeStream = fs.createWriteStream(`./test.tsv`, { encoding: 'utf8', flags : 'a' })
const data = [{
    name: 'Asdf',
  }, {
    name: 'Asdf 2',
  },
]
csv.stringify(data, {
  header: true,
}).pipe(writeStream)
```

```bash
node test.js
node test.js
cat test.tsv
```

Print

```csv
name
Asdf
Asdf 2
name
Asdf
Asdf 2
```

**Comment by jack8966** [comment]
Try to use `a+` flags in your writable stream options.

**Comment by wdavidw** [comment]
Also, note that this is not a CSV issue, but a Node.js stream issue.

**Comment by Zyles** [comment]
a+ does not work either.

So I can't use a stream to loop data into the file?

Is there another way?

**Comment by wdavidw** [comment]
@Zyles, there are a few issues with your code, not related to this package but to your usage of js and streams.

1.`pipe` is called multiple times because it is in a loop. By default, `pipe` closes the writable stream. The first iteration is fine but the second one generates the `write after end` error. You can call `pipe` with the `{end: false}` option to fix this error.
2. `stringify` is an asynchronous function because it extends the Node.js stream API which is asynchronous. When you loop like in your example, you are calling multiple times `stringify` in parallel. As such, they are all writing to your file at the same time and the output will get mixed bytes. Instead, you probably want to run each iteration sequentially.

Here is one way to do it which is far from perfect but which shall work:

```js
const writeStream = fs.createWriteStream(`./test.tsv`, { encoding: 'utf8', flags : 'a' })
const data = [{
    name: 'Asdf',
  }, {
    name: 'Asdf 2',
  },
];

(async () => {
  for (let i = 0; i < 5; i++) {
    await (
      async () => {
        return new Promise( (resolve, reject) => {
          csv.stringify(data, {
            header: true,
          })
          .pipe(writeStream, {end: i === 4})
          .on('finish', resolve)
          .on('unpipe', resolve)
          .on('error', reject)
        })
      }
    )()
  }
})()
```
