### ISSUE TITLE
Error: Object.defineProperty called on non-object

### ISSUE THREAD

**Issue by Claire-Couppie** [adaltas/node-csv#288]
**Describe the bug**

When calling `parse` from `csv-parse`, we sometimes get the following error: `Error: Object.defineProperty called on non-object`.

The calling code:
```
import parse from 'csv-parse/lib/sync';
...
const text = await file.text();
const output = parse(
    text.normalize(),
    {
        columns: true,
        relax_column_count: true,
        fromLine: 2,
        trim: true,
        skip_empty_lines: true,
        delimiter: [';', ',']
    }
);
```
Information from the stack-trace:
```
TypeError: Object.defineProperty called on non-object
  at Object.defineProperty(<anonymous>)
  at Ca(/static/js/12.7e5c6688.chunk.js:1:278)
  at new P(../../../../node_modules/csv-parse/lib/index.js:35:11)
  at p1.exports(../../../../node_modules/csv-parse/lib/sync.js:9:18)
  at ? (pages/logistic-management/warehouses/orders/NewExit.js:787:48)
  at Generator.next(<anonymous>)
  at Ae(8.35a1c8fd.chunk.js:31:46)
```

csv-parse version: 4.15.1

We use csv-parse in the browser only.

**To Reproduce**

I'm sorry not to be able to provide a reproductible scenario, but unfortunately, I've been unable to reproduce this error. However, we are getting several sentry issues every day with this stack, so some of our users experience it.

Users getting the issue were all on Google Chrome, mainly on Windows 10 with some on Windows 8.1 and
 Mac OS X 10.15.7.

**Comment by wdavidw** [comment]
Hi, I will be hard to help. I don't remember any issue related to yours. Are you using a framework like Gatsby.js or Next.js?

[Line 35](https://github.com/adaltas/node-csv/blob/master/packages/csv-parse/lib/index.js#L35) of `csv-parse/lib/index.js` is where we call the parent Node.js Stream Transform class. Since you are in the browser, Node.js isn't there and the framework is placing a browser compatible polyfill of Stream. I would open the `/static/js/12.7e5c6688.chunk.js` code and look at position 278.

You error appear randomly. One possibility is related to the browser version. You could try to use the library alternative module, replacing  `csv-parse/lib/sync` with `csv-parse/lib/es5/sync` or with `csv-parse/lib/browser/sync.js`.

**Comment by Claire-Couppie** [comment]
Thank you very much ! I replaced `csv-parse/lib/sync` by `csv-parse/lib/browser/sync.js` and no new case has shown up today so I think that did it ! I'm closing the issue then.
