### ISSUE TITLE
csv-parse changelog is missing to note breaking changes for v5

### ISSUE THREAD

**Issue by ramya-rao-a** [adaltas/node-csv#313]
The [changelog for version 5.0.0 of csv-parse](https://github.com/adaltas/node-csv/blob/master/packages/csv-parse/CHANGELOG.md#500-2021-11-15) does not mention any breaking changes.

It is helpful for users to understand breaking changes when they upgrade their dependency on csv-parse

**Comment by jacobq** [comment]
Furthermore, some of the "features" (convention-commit tagged as refactors?) are breaking changes, e.g. renaming `skip_lines_with_empty_values` to `skip_records_with_empty_values`.

[`csv-stringify` v6.0.0](https://github.com/adaltas/node-csv/blob/master/packages/csv-stringify/CHANGELOG.md#600-2021-11-15) is also missing notes about breaking changes / migration paths from v5.x to v6.x. here's the [compare](https://github.com/adaltas/node-csv/compare/csv-stringify%405.6.5...csv-stringify%406.0.5) I'm sifting through now...

**Comment by wdavidw** [comment]
Feel free to propose a PR on the project's changelogs

**Comment by jacobq** [comment]
> Feel free to propose a PR on the project's changelogs

I would be willing to do that if I knew what changed/broke, but given the volume (e.g. 530 files touched in the csv-stringify compare linked above) I'll have to just stay on 5.x for now since I can't justify the effort to employer and don't expect to have free time for this in the near future.

Are you aware of any reasons why this project appears to be using [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) and [semver](https://semver.org/) but does not adhere to the part about the `BREAKING CHANGE` (or, alternatively, the `!` suffix) structural elements? In my experience, whenever I have to manually maintain changelogs I always eventually get behind because it requires too much ongoing effort, and I've been inspired by some of the [automation](https://github.com/googleapis/repo-automation-bots) I've seen setup on other projects (e.g. [semantic-release](https://github.com/semantic-release/semantic-release), [danger](https://danger.systems/js/), [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-security-updates/about-dependabot-security-updates), [renovate](https://github.com/renovatebot/renovate#renovate), etc.). I think that merely adding that signal to noteworthy commits, when practical, would help make it easier to sift through.

BTW, my comments / this thread are not intended as criticism (I'm at least as guilty on my own FOSS work) as much as a collaboration/connection point for others running into the same problem. Maybe I'll identify a few changes, others will find some more, and collectively we'll eventually get close enough.

**Comment by wdavidw** [comment]
If you find sth, just update the changelog with a PR. It is not because i miss the syntax in one commit that semver is not respected, it is.

**Comment by jacobq** [comment]
It looks like the issue may be related to the changelog generator being used not picking up on the `!` syntax. (Not sure if you're using lerna for this, but if you are then the problem might be related to [changelog preset using `angular` instead of `conventionalcommits` as mentioned here](https://github.com/lerna/lerna/issues/2668#issuecomment-708632441))
I tried running something like `conventional-changelog -p conventionalcommits -i test.md -s -r 0` on a fork, and it correctly detected breaking changes in `csv-parse` that are missing in the current changelog, e.g.

* **csv-parse:** rename group_columns_by_name option
* **csv-parse:** rename RECORD_INCONSISTENT_FIELDS_LENGTH
* **csv-parse:** rename RECORD_DONT_MATCH_COLUMNS_LENGTH
* **csv-parse:** rename skip_records_with_error
* **csv-parse:** rename skip_records_with_empty_values
* **csv-parse:** rename relax to relax_quotes
 
Not sure about `csv-stringify` yet, but in any case this is good news as it eliminates at least some of the need to sift through all the file changes directly. I intend to make a PR later today, time permitting.
