### ISSUE TITLE
API Documentation?

### ISSUE THREAD

**Issue by JC3** [adaltas/node-csv#360]
Hi!

All of the documentation links I found just seem to contain misc. examples. I am sort of able to glean what some of the API is from them (e.g. I think a "record" is an array, maybe, since the examples sometimes do array-like things to callback parameters named "record"), but is there any plain old API documentation anywhere (e.g. https://lodash.com/docs/4.17.15, https://c2fo.github.io/fast-csv/docs/parsing/methods, https://nodejs.org/dist/latest-v16.x/docs/api/stream.html, etc.)?

Thanks!

**Comment by JC3** [comment]
Thank you; after a good night's sleep; it is easier to sort through now, and I was able to find what I needed there and make it all work.

**Comment by fresheneesz** [comment]
I find this API very unintuitive. Usually you have a page with a list of functions or objects. Here the docs are structured so that each function is a menu section on the side of the site. And each function is its own separate package. What I really want to see here is a single page that says what the parameters are and what their expected structure is, and what return value the function will result in. 

I very much dislike the example-heavy documentation. It explains these things very poorly. For example, look at [this page](https://csv.js.org/generate/api/). The introduction literally says absolutely nothing about what the generate function does or how its used. Instead it talks about details like the fact that there are multiple types of APIs, their implementation similarity, and what style the API is. It then says "the generated output is returned"... Um.. what generated output? What does it look like? Why would I want to generate it? Irrelevant information about the data being stored in memory. And the example makes 0 sense. Why would the generate function result in exactly the record shown? There is literally nothing on that page I would consider "documentation". 

The first thing you should start with here is what the dang thing does! Its frustrating to read docs like this, because it feels like 0 thought was put into what the user of this actually wants to know. Explain the inputs and outputs so the user knows what to expect when using it. Its that simple. Save under-the-hood details for somewhere else. And at least make your examples understandable.

**Comment by wdavidw** [comment]
This is a community effort, I personnaly work on my free time but welcome improvements. Feel free to provide enhancement in the form of pull request with small improvements, meaning steps by steps. The difficulty with this package is how it target so many scenario, js versus ts, web versus nodejs, esm versus commonjs. We are all doing our best and there is certainly room for progress.
