### ISSUE TITLE
Error Lines Property Should Return All Lines of error

### ISSUE THREAD

**Issue by ariona** [adaltas/node-csv#424]
**Describe the bug**

Current Error Lines property only return first occured error in parsing CSV. This should return all errors occured in provided csv string.

**To Reproduce**

```js
parse(`
col1, test
col2
col3, testing
col3
`, {
  trim: true,
  skip_empty_lines: true
})
.on('error', function (err) {
  console.log(err.lines)
})
```

it only return 2, this should return array of lines like [2, 4]

**Comment by wdavidw** [comment]
The demand faces 2 problems:
1. the core of the parser is stream oriented with potentially very long buffers
2. it cannot be reliably be implemented because the error could dependent on escaping and quotations and there is no way to know when a field end (for example, newlines are ok inside a quoted field)
